export interface Dice{
        id: any,
        nickName: string,
        // firstName: string,
        // lastName: string,
        email: string,
        contact: string,
        check: string,
        // cardNumber: string,
        // validity: string,
        // cvv: string,
        // cardholderName: string,
        // cpf: string,
        password: string,
        cep: string,
        address: string,
        no: string,
        complement: string,
        district: string,
        city: string,
}